### ISSUE TITLE
2.9.x-2.12.x version example code

### ISSUE THREAD

**Issue by etsrepo** [thiagoandrade6/cassandra-phantom#14]
there are lot of changes from 2.9.x , I would like to refactor to newer version

**Comment by thiagoandrade6** [comment]
Hi @etsrepo thanks for your message. What exactly do you want to change/improve?

**Comment by etsrepo** [comment]
in new versions fromRow is auto generated, a new store method is auto generated based on case class , no need of concrete abstract class, no need of specifying this to type columns, etc

**Comment by thiagoandrade6** [comment]
Hmm ok, I saw the latest changes. I think I can change it today if you don't mind or do you prefer to open a PR?

**Comment by etsrepo** [comment]
I was testing in my production app but no success because json column type.

**Comment by thiagoandrade6** [comment]
Ok, I'm going to refactor the project according the new phantom-dal guidelines then I will update it here.

**Comment by thiagoandrade6** [comment]
@etsrepo hi, take a look on the latest changes I have made, everything is now working according to the latest version of phantom-dsl. It took me a while to fix the embedded version, since it was throwing timeout, but now the build is passing on TravisCI.

**Comment by etsrepo** [comment]
@thiagoandrade6 thanks, I will check changes with my production code. I will post update soon
