### ISSUE TITLE
Examples very out of date with phantom

### ISSUE THREAD

**Issue by alexflav23** [thiagoandrade6/cassandra-phantom#3]
Hi @thiagoandrade6,

I wanted to thank you for your work in highlighting some of the features offered in phantom through better documentation and examples than perhaps we have made available.

There are however a few very small issues in the implementation, primarily to do with the fact that you are not meant to use models in the way you are highlighting them and you may advocate patterns that for various technical reasons we don't support or test for. There is a lot of reflection code in phantom and a lot of type magic that is very specifically designed to be bullet proof for a certain access pattern, and it can easily break especially since we don't consider it when building the library. I'm aware this is a bit of a chicken and egg problem but nonetheless.

Some of the observations:

- Phantom uses a `Database` to centralise application code and tables and strongly discourages sharing fields in the model.
- Tables are not meant to be initialised outside of a `Database` object like you are advocating.
- The `CassandraUtils class` you have included in the project is somewhat very misleading, since it's unintentionally introducing blocking behaviour to address specifying a consistency level, something phantom can already do with great ease through its existing `Options` API.

Perhaps our efforts would be best spent building a common resource that we can all collaborate on and review since it would provide much better insight for all users and it would follow a pattern we all agree is the "right one".

I will contact you later on this week separately via email to highlight a proposal on how we can achieve this.

**Comment by thiagoandrade6** [comment]
Hi @alexflav23 thanks for your message.

Wonderful! The code of Phantom is a bit tough to understand, since there is a lot of reflection on that, and anyone but one can help me to get a good solution. 

Thanks for the tips in the code, I hope I can learn more from you and together achieve something good for the community. Actually I'm using this piece of code in my daily development, so would be very useful to use the best patterns and strategies phantom can offer.

Looking forward to your email.

**Comment by alexflav23** [comment]
HI @thiagoandrade6,

As usual I am very too busy to reply in due time. I have a few suggestions:

- Remove the sharing of table logic, please have a look at [this blog post](http://websudos.com/blog/post/phantom-tips-tip-1-sharing-table-logic).
- Don't nest `whenReady` calls in tests, you are meant to use for comprehensions for those just like we use throughout phantom tests. It's a bad example for people using futures, since future monadic chains are very common we don't want to mislead them.
- Remove the `Service` abstraction you created, phantom already has a far more powerful `Database` abstraction that does the same thing and a lot more. Read [this](http://websudos.com/blog/post/a-series-on-phantom-part-1-getting-started-with-phantom) for details.

**Comment by thiagoandrade6** [comment]
See this https://github.com/thiagoandrade6/cassandra-phantom/pull/4
