### ISSUE TITLE
Any idea about batch inserting a list of entities using phantom?

### ISSUE THREAD

**Issue by ceecer1** [thiagoandrade6/cassandra-phantom#6]
Hi, I have a use case to insert a list of entities like List[Song], any idea on how to do this efficiently?

**Comment by thiagoandrade6** [comment]
Hi @ceecer1 it took me sometime to understand that, but as far as I know the best way is still iterating over your list and inserting that. Why? Cassandra is distributed by nature, so your insert must goes anywhere around the cluster, it is different from a batch update in a relational database that goes to the same place. Cassandra batch means different here and I suggest to you read this blog post:

https://lostechies.com/ryansvihla/2014/08/28/cassandra-batch-loading-without-the-batch-keyword/

Try to parallel your List using Futures or even Akka.
