### ISSUE TITLE
Examples of how to Implement counter columns?

### ISSUE THREAD

**Issue by dan-mi-sun** [thiagoandrade6/cassandra-phantom#7]
This is an extension to this question:

http://stackoverflow.com/questions/37236128/how-to-increment-cassandra-counter-column-with-phantom-dsl

This question has also been asked [here][1]. 

In [Thiagos example][2] the two tables; 'songs' & 'songs_by_artist' both have the same rows but with different partitions (primary keys / clustering columns)

    CREATE TABLE test.songs (
        song_id timeuuid PRIMARY KEY,
        album text,
        artist text,
        title text
    );
    
    CREATE TABLE test.songs_by_artist (
        artist text,
        song_id timeuuid,
        album text,
        title text,
        PRIMARY KEY (artist, song_id)
    ) WITH CLUSTERING ORDER BY (song_id ASC);

This means inserting, updating and deleting across both tables within the [SongsService][3] works with the same base data / rows.

How would you for example have a table such as 'artist_songs_counts', with columns 'song_id' (K) and 'num_songs' (++) and ensure that 'SongsService' adds corresponding row to each table;  'songs' & 'songs_by_artist'  &  'artist_songs_counts' (where there are different numbers of row but information should be linked, such as the artist info).

    CREATE TABLE test.artist_songs_counts (
        artist text PRIMARY KEY,
        num_songs counter);

  [1]: http://stackoverflow.com/questions/37245031/how-to-implement-cassandra-counter-columns-with-phantom-dsl
  [2]: https://github.com/thiagoandrade6/cassandra-phantom
  [3]: https://github.com/thiagoandrade6/cassandra-phantom/blob/master/src/main/scala/com/cassandra/phantom/modeling/service/SongsService.scala

**Comment by thiagoandrade6** [comment]
I have answered your question on SO http://stackoverflow.com/questions/37245031/how-to-implement-cassandra-counter-columns-with-phantom-dsl/37256783#37256783 take a look and if that fits what you need, please close this issue.

**Comment by dan-mi-sun** [comment]
thanks @thiagoandrade6
