### ISSUE TITLE
Presence of CQL on the main doc is misleading

### ISSUE THREAD

**Issue by alexflav23** [thiagoandrade6/cassandra-phantom#8]
Hi Thiago,

As one of the last pieces of feedback, you are using a lot of straight CQL examples on the readme, which might mislead people from one of phantom's more powerful capabilities, namely the ability to auto-generate tables and to pre-create the keyspace.

You don't actually need to manually create any of the CQL, although I would agree it's useful to have side by side examples to understand exactly how phantom maps to the adjacent CQL code. Let me know what you think.

Regards,
Flavian

**Comment by thiagoandrade6** [comment]
Hi Flavian,

Yes, you are right, there is no need to run any CQL command since the ```DatabaseImpl``` you have created. I will change it accordingly, also with new examples.
