### ISSUE TITLE
How to run this project?

### ISSUE THREAD

**Issue by sasikumarm** [thiagoandrade6/cassandra-phantom#9]
Please add the details about  run

**Comment by thiagoandrade6** [comment]
Hi @sasikumarm although we have tests where you can run using `sbt test`,  this project is not aimed to run using a boot class or similar. The point here is to show how to design your tables and queries using phantom-dsl on top of a cassandra node or cluster. The way you are going to use that is up to you.

**Comment by sasikumarm** [comment]
Thanks for your update.

To run this repo

1. Create tables and index in Cassandra DB ( Execute the below queries)

CREATE TABLE songs (
  song_id uuid,
  title varchar,
  album varchar,
  artist varchar,
  PRIMARY KEY (song_id)
);


CREATE TABLE songs_by_artist (
  song_id uuid,
  title varchar,
  album varchar,
  artist varchar,
  PRIMARY KEY (song_id)
);

CREATE INDEX songs_by_artist ON test.songs_by_artist (artist);

2. Create Main  Class

package com.cassandra.phantom.modeling.main

import com.cassandra.phantom.modeling.connector.Connector
import com.cassandra.phantom.modeling.database.ProductionDatabase
import com.cassandra.phantom.modeling.entity.Song
import com.cassandra.phantom.modeling.service.SongsService
import com.datastax.driver.core.utils.UUIDs
import com.websudos.phantom.reactivestreams._

object CassandraConnecter {
  def main(args: Array[String]) {
    //saveOrUpdate 
    SongsService.saveOrUpdate(Song(UUIDs.timeBased(), "Jai Ho!", "slumdog millionaire", "A R Rahman"))
    
    //getSongsByArtist
    val song = SongsService.getSongsByArtist("A R Rahman")
  }
}

3. sbt run

4. Verify the records insertion in songs and songs_by_artist tables.
a) select * from songs;
b) select * from songs_by_artist;

**Comment by davoudrafati** [comment]
it's not working this way
please just add a new main func to run

**Comment by thiagoandrade6** [comment]
@davoudrafati please, read what I wrote above it above. This project has no runnable method, it shows how to design your tables using phantom and in order to test it, run using `sbt test`.
